import type { BriefResponse } from '../types';

export function makeBrief(): BriefResponse {
  return {
    firm_id: 'strand-okafor',
    firm_name: 'Strand & Okafor LLP',
    attorney_id: 'dana-strand',
    attorney_name: 'Dana Strand',
    generated_at: '2026-05-29T17:00:00Z',
    demo_mode: true,
    resolved_today: [],
    sections: {
      deadlines: {
        count: 1,
        has_critical: true,
        items: [{
          deadline_id: 'dl-mercer-001',
          version: 3,
          matter_id: 'mercer-litigation',
          matter_name: 'Mercer Industries v. Dunlap Construction',
          client_id: 'mercer',
          client_name: 'Mercer Industries',
          description: "Opposition to defendant's motion for summary judgment due",
          due_date: '2026-06-04',
          days_out: 6,
          classification: 'HARD_LEGAL',
          status: 'OPEN',
          verification_status: 'UNCONFIRMED',
          last_confirmed_by: null,
          last_confirmed_at: null,
          is_unconfirmed: false,
          escalation_level: '7_DAY',
          source_type: null,
          source_document_id: null,
          source_excerpt: null,
          court: null,
          jurisdiction: null,
          detected_at: null,
          conflict_detail: null,
        }],
      },
      time_entries: {
        count: 1,
        total_wip_usd: 1500,
        items: [{
          entry_id: 'te-001',
          version: 1,
          matter_id: 'mercer-litigation',
          matter_name: 'Mercer Industries v. Dunlap Construction',
          client_id: 'mercer',
          client_name: 'Mercer Industries',
          attorney_id: 'dana-strand',
          entry_date: '2026-05-28',
          hours: 4,
          amount: 1500,
          narrative: null,
          status: 'PENDING',
          scrubber_flags: [],
          has_block: false,
          has_warn: true,
          task_code: null,
          activity_code: null,
          session_minutes_actual: null,
        }],
      },
      budget_risks: {
        count: 1,
        items: [{
          client_id: 'acme',
          client_name: 'Acme Commercial Partners LLC',
          budget_cap: 15000,
          budget_billed: 9000,
          approved_unbilled: 2700,
          total_committed: 11700,
          utilization_pct: 78,
          alert_status: 'WARN',
          threshold_pct: 75,
        }],
      },
      client_silence: {
        count: 1,
        items: [{
          matter_id: 'whitmore-employment-2026',
          matter_name: 'Whitmore Group Employment Advisory',
          client_id: 'whitmore',
          client_name: 'Whitmore Group',
          days_since_contact: 16,
          threshold_days: 14,
          last_contact_date: '2026-05-13',
          comm_draft_id: null,
        }],
      },
      anomalies: {
        count: 1,
        items: [{
          escalation_id: 'anomaly-te-001',
          matter_id: 'mercer-litigation',
          entity_id: 'te-001',
          entity_type: 'time_entry',
          risk_level: 'ELEVATED',
          priority: 2,
          what_is_happening: 'MISSING NARRATIVE on entry te-001',
          why_it_matters: 'Entry has no narrative. Narrative required before billing.',
          what_litt_has_done: 'Flagged the entry.',
          what_attorney_must_decide: 'Add a narrative before approval.',
          created_at: '2026-05-29T12:00:00Z',
        }],
      },
      compound_escalations: {
        count: 0,
        items: [],
      },
      inbox_items: {
        count: 0,
        items: [],
      },
    },
  };
}
