/**
 * InboundCard — email triage card for a single inbound message.
 * Shows sender, urgency badge, excerpt, action items, and action buttons.
 */

import type { BriefInboundItem } from '../types';
import { GeminiLabel } from './shared/GeminiLabel';

interface InboundCardProps {
  item: BriefInboundItem;
  onDismiss?: (messageId: string) => void;
  onApproveReply?: (messageId: string) => void;
}

const URGENCY_STYLE: Record<string, { bg: string; color: string; border: string }> = {
  HIGH:   { bg: 'rgba(155,45,35,.08)', color: '#9B2D23', border: 'rgba(155,45,35,.3)' },
  MEDIUM: { bg: 'rgba(169,132,53,.06)', color: '#A98435', border: 'rgba(169,132,53,.3)' },
  LOW:    { bg: 'rgba(29,158,117,.06)', color: '#1D9E75', border: 'rgba(29,158,117,.25)' },
};

const ROLE_LABEL: Record<string, string> = {
  client:             'Client',
  opposing_counsel:   'Opp. Counsel',
  court:              'Court',
  vendor:             'Vendor',
};

export function InboundCard({ item, onDismiss, onApproveReply }: InboundCardProps) {
  const urg = URGENCY_STYLE[item.urgency] ?? URGENCY_STYLE.LOW;
  const roleLabel = ROLE_LABEL[item.from_role] ?? item.from_role;
  const isOpposingCounsel = item.from_role === 'opposing_counsel';
  const hasReply = !!item.suggested_reply_comm_id;

  return (
    <div style={{
      border:       `1px solid ${urg.border}`,
      borderRadius: 10,
      background:   urg.bg,
      padding:      '12px 14px',
      display:      'grid',
      gap:          10,
    }}>
      {/* Header */}
      <div style={{ display: 'flex', alignItems: 'start', gap: 10, flexWrap: 'wrap' }}>
        {/* Urgency badge */}
        <span style={{
          flexShrink:    0,
          background:    urg.color,
          color:         '#FFFFFF',
          borderRadius:  4,
          padding:       '2px 7px',
          fontFamily:    'var(--font-mono)',
          fontSize:      9,
          fontWeight:    700,
          letterSpacing: '0.06em',
          textTransform: 'uppercase',
        }}>
          {item.urgency}
        </span>

        {/* Role badge */}
        <span style={{
          flexShrink:    0,
          background:    isOpposingCounsel ? 'rgba(155,45,35,.1)' : 'rgba(20,34,31,.07)',
          color:         isOpposingCounsel ? '#9B2D23' : '#5C6B64',
          border:        `1px solid ${isOpposingCounsel ? 'rgba(155,45,35,.3)' : 'rgba(20,34,31,.18)'}`,
          borderRadius:  4,
          padding:       '2px 7px',
          fontFamily:    'var(--font-mono)',
          fontSize:      9,
          fontWeight:    600,
          letterSpacing: '0.05em',
          textTransform: 'uppercase',
        }}>
          {roleLabel}
        </span>

        <div style={{ flex: 1, minWidth: 0 }}>
          <div style={{ fontSize: 13, fontWeight: 600, color: '#14221F', lineHeight: 1.3 }}>
            {item.from_name}
          </div>
          <div style={{ fontSize: 11, fontFamily: 'var(--font-mono)', color: '#5C6B64', marginTop: 2 }}>
            {item.wait_days > 0 ? `${item.wait_days}d waiting` : 'New today'}
            {item.matter_id ? ` · ${item.matter_id}` : ''}
          </div>
        </div>

        {/* Opposing counsel warn */}
        {isOpposingCounsel && (
          <span style={{
            flexShrink:    0,
            background:    '#FFF3CD',
            color:         '#856404',
            border:        '1px solid #FFCA2C',
            borderRadius:  4,
            padding:       '2px 7px',
            fontFamily:    'var(--font-mono)',
            fontSize:      9,
            fontWeight:    600,
            letterSpacing: '0.05em',
            textTransform: 'uppercase',
          }}>
            WARN — no auto-reply
          </span>
        )}
      </div>

      {/* Message excerpt */}
      {item.message_excerpt && (
        <p style={{
          margin:      0,
          fontSize:    12,
          color:       '#14221F',
          lineHeight:  1.5,
          fontStyle:   'italic',
          borderLeft:  `2px solid ${urg.border}`,
          paddingLeft: 8,
        }}>
          "{item.message_excerpt}"
        </p>
      )}

      {/* Gemini summary */}
      {item.summary && (
        <div>
          <div style={{ display: 'flex', alignItems: 'center', gap: 6, marginBottom: 4 }}>
            <GeminiLabel title="Summary generated by Gemini 2.5 Pro" />
            <span style={{ fontSize: 10, fontFamily: 'var(--font-mono)', color: '#5C6B64' }}>
              Summary
            </span>
          </div>
          <p style={{ margin: 0, fontSize: 12, color: '#14221F', lineHeight: 1.45 }}>
            {item.summary}
          </p>
        </div>
      )}

      {/* Action items */}
      {item.action_items.length > 0 && (
        <div>
          <div style={{ fontSize: 10, fontFamily: 'var(--font-mono)', textTransform: 'uppercase', letterSpacing: '0.08em', color: '#5C6B64', marginBottom: 4 }}>
            Action items
          </div>
          <ul style={{ margin: 0, paddingLeft: 16, display: 'grid', gap: 3 }}>
            {item.action_items.map((ai, i) => (
              <li key={i} style={{ fontSize: 12, color: '#14221F', lineHeight: 1.4 }}>{ai}</li>
            ))}
          </ul>
        </div>
      )}

      {/* Action buttons */}
      {!isOpposingCounsel && (
        <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap' }}>
          {hasReply && (
            <button
              onClick={() => onApproveReply?.(item.message_id)}
              style={{
                background:   '#14221F',
                color:        '#FFFFFF',
                border:       'none',
                borderRadius: 6,
                padding:      '6px 12px',
                fontSize:     12,
                fontWeight:   600,
                cursor:       'pointer',
              }}
            >
              Approve reply →
            </button>
          )}
          <button
            onClick={() => onDismiss?.(item.message_id)}
            style={{
              background:   'transparent',
              color:        '#5C6B64',
              border:       '1px solid rgba(20,34,31,.2)',
              borderRadius: 6,
              padding:      '6px 12px',
              fontSize:     12,
              cursor:       'pointer',
            }}
          >
            Dismiss
          </button>
        </div>
      )}
    </div>
  );
}
